# LEARN NUMPY 

In [7]:
!pip install numpy

In [8]:
import numpy as np

# 1.Create

In [9]:
data = np.random.rand(2,3,4)
zeroes = np.zeros((2,2,2))
full = np.full((2,2,2), 7)
ones = np.ones((2,2,2))

In [10]:
data

array([[[0.97032202, 0.66609263, 0.14832738, 0.02910377],
        [0.85893231, 0.25985762, 0.87951367, 0.99163121],
        [0.85821672, 0.3620032 , 0.41980322, 0.69795978]],

       [[0.8367869 , 0.23905603, 0.35001033, 0.10436574],
        [0.16540754, 0.73223479, 0.30443321, 0.282907  ],
        [0.01318899, 0.86450643, 0.93461981, 0.89035466]]])

In [11]:
zeroes

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [12]:
full

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [13]:
ones

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [14]:
arr = np.array([[1,2,3],[1,2,3]])

In [15]:
arr

array([[1, 2, 3],
       [1, 2, 3]])

In [16]:
type(arr)

numpy.ndarray

# 2.Read

In [17]:
#Attributes
shape = data.shape
size = data.size
types = data.dtype

In [18]:
shape

(2, 3, 4)

In [19]:
size

24

In [20]:
types

dtype('float64')

In [27]:
# Slicing
arr = data[0]
slicer = data[0][0:2]
reverse = data[-1]
singleval = data[0][0][0]

In [28]:
data

array([[[0.97032202, 0.66609263, 0.14832738, 0.02910377],
        [0.85893231, 0.25985762, 0.87951367, 0.99163121],
        [0.85821672, 0.3620032 , 0.41980322, 0.69795978]],

       [[0.8367869 , 0.23905603, 0.35001033, 0.10436574],
        [0.16540754, 0.73223479, 0.30443321, 0.282907  ],
        [0.01318899, 0.86450643, 0.93461981, 0.89035466]]])

In [29]:
arr

array([[0.97032202, 0.66609263, 0.14832738, 0.02910377],
       [0.85893231, 0.25985762, 0.87951367, 0.99163121],
       [0.85821672, 0.3620032 , 0.41980322, 0.69795978]])

In [30]:
slicer

array([[0.97032202, 0.66609263, 0.14832738, 0.02910377],
       [0.85893231, 0.25985762, 0.87951367, 0.99163121]])

In [31]:
reverse

array([[0.8367869 , 0.23905603, 0.35001033, 0.10436574],
       [0.16540754, 0.73223479, 0.30443321, 0.282907  ],
       [0.01318899, 0.86450643, 0.93461981, 0.89035466]])

In [32]:
singleval

0.9703220173468131

# 3. Update

In [35]:
list1 = np.random.rand(10)
list2 = np.random.rand(10)

In [36]:
list2

array([0.54182903, 0.58541424, 0.09046399, 0.77559305, 0.08002383,
       0.93288083, 0.616835  , 0.63579428, 0.30390471, 0.60441607])

In [37]:
#Basic Math
add = np.add(list1, list2)
sub = np.subtract(list1, list2)
div = np.divide(list1, list2)
mult = np.multiply(list1, list2)
dot = np.dot(list1, list2)

In [38]:
add

array([0.96711683, 0.94387678, 0.62489317, 1.41132092, 0.37570436,
       1.86405821, 0.91973481, 1.27787642, 0.74655301, 1.33551672])

In [39]:
sub

array([-0.11654122, -0.2269517 ,  0.44396519, -0.13986518,  0.21565669,
       -0.00170345, -0.31393518,  0.00628785,  0.13874359,  0.12668457])

In [40]:
div

array([0.78491145, 0.6123229 , 5.90764555, 0.8196668 , 3.69490585,
       0.99817399, 0.49105484, 1.00988975, 1.45653648, 1.20959828])

In [41]:
mult

array([0.23043328, 0.20984908, 0.0483466 , 0.49306612, 0.02366149,
       0.86867753, 0.1868392 , 0.40823215, 0.1345229 , 0.44188898])

In [42]:
dot

3.0455173254294436

In [43]:
# Stat Functions
sqrt = np.sqrt(25)
ab = np.abs(-2)
power = np.power(2,7)
log = np.log(25)
exp = np.exp([2,3])
mins = np.min(list1)
maxs = np.max(list1)

In [44]:
sqrt

5.0

In [45]:
ab

2

In [46]:
power

128

In [47]:
log

3.2188758248682006

In [48]:
exp

array([ 7.3890561 , 20.08553692])

In [49]:
mins

0.2956805248590719

In [50]:
maxs

0.9311773831233258

In [51]:
data[0][0][0] = 0

In [52]:
data

array([[[0.        , 0.66609263, 0.14832738, 0.02910377],
        [0.85893231, 0.25985762, 0.87951367, 0.99163121],
        [0.85821672, 0.3620032 , 0.41980322, 0.69795978]],

       [[0.8367869 , 0.23905603, 0.35001033, 0.10436574],
        [0.16540754, 0.73223479, 0.30443321, 0.282907  ],
        [0.01318899, 0.86450643, 0.93461981, 0.89035466]]])

In [53]:
data.sort()

In [54]:
data

array([[[0.        , 0.02910377, 0.14832738, 0.66609263],
        [0.25985762, 0.85893231, 0.87951367, 0.99163121],
        [0.3620032 , 0.41980322, 0.69795978, 0.85821672]],

       [[0.10436574, 0.23905603, 0.35001033, 0.8367869 ],
        [0.16540754, 0.282907  , 0.30443321, 0.73223479],
        [0.01318899, 0.86450643, 0.89035466, 0.93461981]]])

In [55]:
data.shape

(2, 3, 4)

In [57]:
# -1 stands for auto
data = data.reshape((2,2,-1))
data.shape

(2, 2, 6)

In [58]:
zeroes = np.zeros((8))
print(zeroes)
zeroes = np.append(zeroes, [3,4])
print(zeroes)

[0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 3. 4.]


In [59]:
zeroes = np.insert(zeroes, 2, 1)

In [60]:
zeroes

array([0., 0., 1., 0., 0., 0., 0., 0., 0., 3., 4.])

# 4.Delete

In [61]:
data

array([[[0.        , 0.02910377, 0.14832738, 0.66609263, 0.25985762,
         0.85893231],
        [0.87951367, 0.99163121, 0.3620032 , 0.41980322, 0.69795978,
         0.85821672]],

       [[0.10436574, 0.23905603, 0.35001033, 0.8367869 , 0.16540754,
         0.282907  ],
        [0.30443321, 0.73223479, 0.01318899, 0.86450643, 0.89035466,
         0.93461981]]])

In [62]:
np.delete(data, 0, axis=1)

array([[[0.87951367, 0.99163121, 0.3620032 , 0.41980322, 0.69795978,
         0.85821672]],

       [[0.30443321, 0.73223479, 0.01318899, 0.86450643, 0.89035466,
         0.93461981]]])

In [63]:
np.save("new array", data)

In [66]:
test = np.load("new array.npy")

In [67]:
test

array([[[0.        , 0.02910377, 0.14832738, 0.66609263, 0.25985762,
         0.85893231],
        [0.87951367, 0.99163121, 0.3620032 , 0.41980322, 0.69795978,
         0.85821672]],

       [[0.10436574, 0.23905603, 0.35001033, 0.8367869 , 0.16540754,
         0.282907  ],
        [0.30443321, 0.73223479, 0.01318899, 0.86450643, 0.89035466,
         0.93461981]]])